Add lama
ITMO-NSS-team/pytsbe pull request #14
Opened 2022-12-26 09:06 UTC by valer1435

Add LAMA model to benchmark

2022-12-26 11:38 UTC, Dreamlone requested changes
В целом всё гуд - довольно гладко все интегрировал 
Можешь заодно CI/CD пайплайн настроить в репозитории, чтобы тесты запускались автоматически при создании PR'а как это сделано в репозитории с FEDOT'м. Но это опционально

2022-12-26 11:38 UTC, Dreamlone commented on examples/univariate_prepare_visualizations.py
> +    #plots_creator.execution_time_comparison()
Стоит вернуть как было - закомментированные участки в примерах не есть хорошо
Плюс `r` может для единообразия из пути стоит убрать

2022-12-26 11:38 UTC, Dreamlone commented on pytsbe/report/report.py
> +    def time_execution_table(self, aggregation: Union[str, list] = None, agg_method: str = 'mean'):
Стоит занести новый параметр в docstring и перечислить его возможные значения

2022-12-26 11:38 UTC, Dreamlone commented on requirements.txt
> +lightautoml
Ты уверен, что ничего не поламается? - нужно проверить. Я например не просто так задавал конкретные версии у autots и fbprophet - помню в свое время довольно сильно намучился с переходом между версиями

2023-01-18 11:27 UTC, valer1435 commented on examples/univariate_prepare_visualizations.py
> +    #plots_creator.execution_time_comparison()
[Убрал лишнее](https://github.com/ITMO-NSS-team/pytsbe/pull/14/commits/780f03340a35a1ea1906d821f49150a4d338dba3#diff-763fc52eb8f92e4fb44b9144a0d46bd7f4c429863af14d7fc0f3fde6586b561cR6-R9)

2023-01-18 11:27 UTC, valer1435 commented on requirements.txt
> +lightautoml
[Согласен](https://github.com/ITMO-NSS-team/pytsbe/pull/14/commits/780f03340a35a1ea1906d821f49150a4d338dba3#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552R1-R5), может сломаться

2023-01-21 10:16 UTC, Dreamlone approved these changes
Хорошо интегрировал Ламу 
Можешь вливать, но поправь плиз два момента:
1) Стоит удалить файлы вроде pytsbe/report/preparers/__pycache__/metrics.cpython-38.pyc и занести их в gitignore
2) Файл lama_forecaster.py стоит перенести из `automl_forecasters` в папку `models`.  Дело в том, что в `automl_forecasters` содержатся классы потомки от `AutoMLForecaster` и задача их такая: помочь AutoML фреймворкам, которые не умеют прогнозировать временные ряды нативно, усваивать временные ряды. А LAMA вполне себе может

2023-02-26 08:40 UTC, merged