Add new series
ITMO-NSS-team/pytsbe pull request #16
Opened 2023-09-14 14:00 UTC by valer1435

Series from M4 were added

2023-09-14 14:23 UTC, kasyanovse requested changes

2023-09-14 14:23 UTC, kasyanovse commented on examples/univariate_prepare_report.py
> +    metrics_processor = MetricsReport(working_dir=r'Z:\pytsbe\5_launches_10_minutes')
Наверное, опечатка? Зачем нужен абсолютный путь?

2023-09-14 14:23 UTC, kasyanovse commented on examples/univariate_prepare_report.py
> +    metrics_table = metrics_processor.metric_table(metrics=['MAE', 'SMAPE'],
А может стоит попробовать добавить MASE? Раз уж он используется в соревновании по M4.

2023-09-14 14:23 UTC, kasyanovse commented on examples/univariate_prepare_visualizations.py
> +                               folder_for_plots='./')
Аналогичный вопрос к абсолютному пути.

2023-09-14 14:23 UTC, kasyanovse commented on experiments/univariate/configuration.yaml
> +             AutoGluon: { 'timeout': 600 },
А 10 часов в таймауте не слишком жестко?))

2023-09-14 14:23 UTC, kasyanovse commented on experiments/univariate/configuration.yaml
> +horizons: [ 10, 20, 30, 40, 50, 60, 70, 80, 90, 100 ]
Как думаешь, может стоит добавить горизонт поменьше? Типа 2 или 3, или 4, или 5?

2023-09-14 14:23 UTC, kasyanovse commented on pytsbe/models/industrial_SSA_ar.py
> +        if params is not None:
Проверка на `None` идет здесь, а двумя строками выше `params` распаковывается в `super().__init__(**params)`

2023-09-14 14:23 UTC, kasyanovse commented on pytsbe/models/industrial_SSA_ar.py
> +        if params is not None:
А зачем вообще проверка, если params всегда словарь?

2023-09-14 14:23 UTC, kasyanovse commented on pytsbe/models/industrial_SSA_ar.py
> +                                                            params={'n_components': 6, 'window_size': n,
Здесь `n_components` равно 6, а в конструкторе выше было задано равным 5. Это не опечатка, случаем?

2023-09-14 14:25 UTC, kasyanovse commented on experiments/univariate/configuration.yaml
> +horizons: [ 10, 20, 30, 40, 50, 60, 70, 80, 90, 100 ]
Вообще, ряд с размерами окон можно взять в виде геометрической регрессии. Так можно будет взять поменьше окон и не потерять в качестве.

2023-09-14 14:30 UTC, valer1435 commented on pytsbe/models/industrial_SSA_ar.py
> +                                                            params={'n_components': 6, 'window_size': n,
Его вообще надо выпилить из pr, он тут ни к чему(

2023-09-14 14:30 UTC, valer1435 commented on experiments/univariate/configuration.yaml
> +             AutoGluon: { 'timeout': 600 },
В глюоне таймаут в секундах

2023-09-14 15:18 UTC, nicl-nno commented on experiments/univariate/configuration.yaml
> +horizons: [ 10, 20, 30, 40, 50, 60, 70, 80, 90, 100 ]
Точно не помешает горизонт 1. Как вырожденный случай.

2023-09-16 12:46 UTC, valer1435 commented on examples/univariate_prepare_report.py
> +    metrics_table = metrics_processor.metric_table(metrics=['MAE', 'SMAPE'],
Тогда нужно будет сохранять и тренировочные данные тоже, чегоо сейчас не делается. Стоит отложить в следующий pr

2023-09-16 12:53 UTC, valer1435 commented on examples/univariate_prepare_report.py
> +    metrics_processor = MetricsReport(working_dir=r'Z:\pytsbe\5_launches_10_minutes')
[Исправил](https://github.com/ITMO-NSS-team/pytsbe/pull/16/commits/b4f283fbace573ba928cde92fa7728dcf5f2ed6d#diff-bde6fb505bf67a777b490427b579b0303039b502aadcb1322397fc139442463bR10)

2023-09-16 12:53 UTC, valer1435 commented on examples/univariate_prepare_visualizations.py
> +                               folder_for_plots='./')
[Исправил](https://github.com/ITMO-NSS-team/pytsbe/pull/16/commits/b4f283fbace573ba928cde92fa7728dcf5f2ed6d#diff-763fc52eb8f92e4fb44b9144a0d46bd7f4c429863af14d7fc0f3fde6586b561cR6)

2023-09-16 12:56 UTC, valer1435 commented on experiments/univariate/configuration.yaml
> +horizons: [ 10, 20, 30, 40, 50, 60, 70, 80, 90, 100 ]
[Добавил](https://github.com/ITMO-NSS-team/pytsbe/pull/16/files#diff-a35ee21d997906b8a6ccf93fe68dac32ecbd149bb99d6bd2728543fb690a48fbR24)

2023-09-16 12:56 UTC, valer1435 commented on pytsbe/models/industrial_SSA_ar.py
> +                                                            params={'n_components': 6, 'window_size': n,
Выпилил файл

2023-09-16 18:35 UTC, nicl-nno approved these changes

2023-09-17 07:25 UTC, kasyanovse approved these changes

2023-09-18 20:09 UTC, merged