add nns
ITMO-NSS-team/pytsbe pull request #21
Opened 2023-12-13 14:18 UTC by valer1435

2023-12-13 14:18 UTC, pep8speaks commented
Hello @valer1435! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`pytsbe/models/nn_forecasters/auto_gru_forecaster.py`](https://github.com/ITMO-NSS-team/pytsbe/blob/524e51e2daa6a0debcaf825d49b14131e15660b1/pytsbe/models/nn_forecasters/auto_gru_forecaster.py):

> [Line 29:1](https://github.com/ITMO-NSS-team/pytsbe/blob/524e51e2daa6a0debcaf825d49b14131e15660b1/pytsbe/models/nn_forecasters/auto_gru_forecaster.py#L29): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file









* In the file [`pytsbe/models/nn_forecasters/auto_timesnet_forecater.py`](https://github.com/ITMO-NSS-team/pytsbe/blob/524e51e2daa6a0debcaf825d49b14131e15660b1/pytsbe/models/nn_forecasters/auto_timesnet_forecater.py):

> [Line 28:1](https://github.com/ITMO-NSS-team/pytsbe/blob/524e51e2daa6a0debcaf825d49b14131e15660b1/pytsbe/models/nn_forecasters/auto_timesnet_forecater.py#L28): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2023-12-14 07:39 UTC, kasyanovse requested changes

2023-12-14 07:39 UTC, kasyanovse commented on pytsbe/models/nn_forecasters/auto_gru_forecaster.py
> +        return model
Это все можно прописать в `NNForecaster`, передавая ему на вход конструктора класс модели.

2023-12-14 07:39 UTC, kasyanovse commented on pytsbe/models/nn_forecasters/auto_gru_forecaster.py
> +        gpus = int(self.accelerator == 'gpu')
Нет `super().__init__()`.

2023-12-14 12:49 UTC, valer1435 commented on pytsbe/models/nn_forecasters/auto_gru_forecaster.py
> +        gpus = int(self.accelerator == 'gpu')
Это не инициализатор, поэтому не обязательно. Или я неправильно понял?

2023-12-14 14:08 UTC, kasyanovse commented on pytsbe/models/nn_forecasters/auto_gru_forecaster.py
> +        gpus = int(self.accelerator == 'gpu')
Не заметил что это не `__init__`))

2023-12-14 14:09 UTC, kasyanovse approved these changes

2023-12-27 15:31 UTC, merged